refactor(dataverse): create card component
okp4/dataverse-portal pull request #121
Opened 2023-03-22 13:24 UTC by ErikssonJoakim

Refactor the dataverse card to a proper component

2023-03-22 16:01 UTC, fredericvilcot reviewed
Good, just a minor remark

2023-03-23 10:22 UTC, ccamel requested changes

2023-03-23 11:02 UTC, AnjaMis commented on src/component/card/dataverseCard/dataverseCard.tsx
> +import ReactMarkdown from 'react-markdown'
Yes, you right, it's better that way. We fixed it now :)

2023-03-23 11:34 UTC, lolottetheclash approved these changes
Good job :)

2023-03-23 14:02 UTC, fredericvilcot approved these changes

2023-03-23 14:04 UTC, merged