Refactor/remove unnecessary navigation state for active sections
okp4/dataverse-portal pull request #188
Opened 2023-04-20 13:53 UTC by 0xLodz

This PR removes the governance navigation state management. This state is not required because active links are managed from component props. The router manage and to pass these props from the governance component. Thanks @fredericvilcot for [pointing this out](https://github.com/okp4/dataverse-portal/pull/180#discussion_r1172545430)!

2023-04-20 14:17 UTC, fredericvilcot requested changes
Great, thank you, just a little remark that can improve the way you use the `NavLink` item.

2023-04-20 14:17 UTC, fredericvilcot commented on src/ui/page/dataverse/dataspace/governance/governanceNavigation.tsx
> +  activeSubsectionId
This prop is not needed

2023-04-21 07:19 UTC, lolottetheclash approved these changes
Good for me ! 👍

2023-04-21 07:29 UTC, fredericvilcot approved these changes
Great, thx ☺️

2023-04-21 07:39 UTC, merged