Feat/implement field copy in core & audit metadata
okp4/dataverse-portal pull request #234
Opened 2023-05-12 07:52 UTC by balteo

This PR implements https://github.com/okp4/dataverse-portal/issues/219

2023-05-15 08:46 UTC, fredericvilcot commented on src/ui/component/copyToClipboard/copyToClipboard.scss
> +@keyframes show {
I'm not sure you need an extra `keyframe` here, you could simply use the `transition` rule no?

2023-05-15 09:17 UTC, ccamel requested changes

2023-05-15 09:17 UTC, ccamel commented on src/ui/component/copyToClipboard/copyToClipboard.tsx
> +  const [iconName, setIconName] = useState<IconName>(`copy-${theme}`)
Restrict the type of the icons of the state, you just want a few subset of the `IconNames`. So specify the union types explicitly.

2023-05-17 10:02 UTC, ccamel commented
Thanks @balteo. This feature has now been consolidated in the PR https://github.com/okp4/dataverse-portal/pull/238.

2023-05-17 10:02 UTC, closed without merging