Feat/create list and list-item components
okp4/dataverse-portal pull request #328
Opened 2023-06-26 05:36 UTC by 0xLodz

## List and ListItem components

This PR introduces the generic `List` and `ListItems` components, designed to provide interactive and customisable list elements. The component is built with the intention of being easily integrated into various parts of the application that display list items, such as dataset sharing.

## Usage
```tsx
export const TestListExemple: FC = () => {
  const handleClick = () => {
    console.log('clicked')
  }
  return (
    <List>
      {[1, 2, 3].map((data, i) => (
        <ListItem key={i} onClick={handleClick}>
          <div>{data}</div>
          <div>{data}</div>
        </ListItem>
      ))}

      <ListItem>I&apos;m a string</ListItem>
    </List>
  )
}
```

2023-06-26 15:18 UTC, fredericvilcot commented on src/ui/component/list/list.tsx
> +      'pointer-cursor': onClick
Maybe something like `clickable` would have been more appropriated here :)

2023-06-27 07:17 UTC, 0xLodz commented on src/ui/component/list/list.tsx
> +      'pointer-cursor': onClick
Sounds a more appropriated name 👍

2023-06-27 07:23 UTC, lolottetheclash requested changes
It think you'd have to manage the space in a different way than via flex, as the elements are wrongly placed according to which you pass (see screenshot).
You'd also need to give them a bit of space between each other, because when the list item is shrunk, they're stuck together.
<img width="1115" alt="Capture d’écran 2023-06-27 à 09 19 06" src="https://github.com/okp4/dataverse-portal/assets/35332974/f15b011c-1ee9-49d5-891e-81a455a850d3">

2023-06-27 07:23 UTC, lolottetheclash commented on src/ui/component/list/list.scss
> +    font-family: 'Noto Sans', sans-serif;
you should use our fonts mixins ;)

2023-06-27 08:32 UTC, ccamel approved these changes
LGTM!

2023-06-27 10:25 UTC, lolottetheclash requested changes
I think that the problem persists if you look at the screenshots here:
![Capture d’écran 2023-06-27 à 12 21 37](https://github.com/okp4/dataverse-portal/assets/35332974/55fdcf87-79c8-40c2-81e0-3c96495eaf7b)

Also, when I'm looking at the figma, content should start right after the first element:

![Capture d’écran 2023-06-27 à 12 20 49](https://github.com/okp4/dataverse-portal/assets/35332974/79d7d333-f9dd-4587-9756-56b94c6be492)

2023-06-27 14:13 UTC, 0xLodz commented
@lolottetheclash Thank you for your detailed feedback! The component has been updated according to the latest mockup. As we always have content, I made it required. It reduced the number of combinations of grid template columns from 9 to 3.

2023-06-27 14:21 UTC, fredericvilcot commented on src/ui/component/list/list.tsx
> +  console.log('render')
🫣😝

2023-06-27 14:28 UTC, 0xLodz commented on src/ui/component/list/list.tsx
> +  console.log('render')
Oops sorry! Fixed.

2023-06-27 14:29 UTC, fredericvilcot approved these changes
LGTM! 👌

2023-06-28 09:07 UTC, lolottetheclash requested changes
It's working well, last remarks and it will be good to go !

2023-06-28 09:07 UTC, lolottetheclash commented on src/ui/component/list/list.tsx
> +  rightElement: ReactElement | undefined
you can remove `undefined` and update it with optional 😉

2023-06-28 12:26 UTC, lolottetheclash approved these changes
good for me, thanks !

2023-06-28 14:40 UTC, merged